# Generated by Django 4.1.1 on 2023-07-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.IntegerField()),
            ],
        ),
    ]
